In [2]:
import tictac as tic
import numpy as np

In [9]:
num_gens = 7
players = [tic.Player(),tic.Player()]
gen_curr = tic.Generation(players,num_games=50)
player_best = gen_curr.play_games()
vx_old = np.copy(vx)
vy_old = np.copy(vy)
for i in range(num_gens-1):
    gen_curr.clip_data()
    vx,vy = tic.augment_v(gen_curr.value_data,gen_curr.value_tar)
    ax,ay = gen_curr.action_data,gen_curr.action_tar
    vx = np.concatenate((vx,vx_old))
    vy = np.concatenate((vy,vy_old))
    player_challenger = tic.Player()
    player_challenger.train(vx,vy,ax,ay)
    if i == 0:
        player_best.train(vx,vy,ax,ay)
    gen_curr = tic.Generation([player_best,player_challenger],num_games=50)
    player_best = gen_curr.play_games()
    player_best.wins = 0
    vx_old = np.copy(vx)
    vy_old = np.copy(vy)

        

Train on 8215 samples, validate on 913 samples
Epoch 1/3
8215/8215 [==============================] - 2s 276us/sample - loss: 0.2342 - val_loss: 0.2051
Epoch 2/3
8215/8215 [==============================] - 1s 125us/sample - loss: 0.1779 - val_loss: 0.1627
Epoch 3/3
8215/8215 [==============================] - 1s 124us/sample - loss: 0.1498 - val_loss: 0.1502
Train on 124790 samples, validate on 13866 samples
Epoch 1/10
124790/124790 [==============================] - 23s 184us/sample - loss: 0.3700 - val_loss: 0.3929
Epoch 2/10
124790/124790 [==============================] - 22s 174us/sample - loss: 0.3315 - val_loss: 0.4000
Epoch 3/10
124790/124790 [==============================] - 22s 175us/sample - loss: 0.3198 - val_loss: 0.3828
Epoch 4/10
124790/124790 [==============================] - 22s 177us/sample - loss: 0.3135 - val_loss: 0.3727
Epoch 5/10
124790/124790 [==============================] - 22s 177us/sample - loss: 0.3101 - val_loss: 0.3683
Epoch 6/10
124790/124790 [======

[20, 20, 56, 1, 1, 1, 38, 73, 73, 109, 74, 38, 74, 38, 74, 20, 56, 73, 38, 38]
[[ 0.  1.  0.  0.  0.]
 [ 0.  1.  0.  0. -1.]
 [ 0.  0.  0. -1.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0. -1.  0.]] 

[19, 87, 70, 70, 53, 87, 19, 70, 1, 1, 53, 1, 36, 53, 87, 36, 53, 36, 36]
[[ 0.  1.  0.  0.  0.]
 [ 0.  1.  0.  0. -1.]
 [ 0.  1.  0. -1.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0. -1.  0.]] 

Game 3 Done 8 568
[71, 48, 25, 117, 25, 48, 1, 1, 1, 48, 71, 48, 25, 117, 48, 94, 25, 1, 71, 25, 48, 48, 48, 94, 25]
[[0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 

[46, 90, 46, 133, 68, 46, 46, 24, 24, 24, 68, 24, 1, 68, 1, 68, 90, 24, 24, 46, 24, 24, 46, 68]
[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0. -1.  0.]] 

no children
[23, 1, 86, 86, 1, 1, 1, 44, 1, 44, 44, 128, 65, 23, 65, 107, 127, 65, 44, 23, 23, 44, 23]
[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  1.  

[1, 38, 20, 20, 38, 127, 38, 74, 1, 1, 74, 109, 38, 20, 20, 56, 56, 74, 92, 20]
[[ 0.  0.  0.  0.  0.]
 [-1.  1.  0.  0.  0.]
 [ 0.  1.  0.  0.  1.]
 [-1.  0.  0.  0.  0.]
 [ 0.  0.  0. -1.  0.]] 

no children
[19, 1, 87, 53, 19, 87, 53, 53, 36, 36, 36, 1, 69, 70, 103, 36, 53, 36, 19]
[[ 0.  1.  0.  0.  0.]
 [-1.  1.  0.  0.  0.]
 [ 0.  1.  0.  0.  1.]
 [-1.  0.  0.  0.  0.]
 [ 0.  0.  0. -1.  0.]] 

Game 8 Done 8 718
[25, 93, 48, 25, 1, 71, 1, 71, 25, 71, 48, 25, 48, 48, 1, 71, 116, 48, 71, 25, 71, 25, 93, 25, 25]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 

[68, 46, 24, 68, 68, 90, 24, 24, 46, 46, 1, 24, 46, 24, 24, 68, 24, 46, 46, 90, 24, 24, 90, 89]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0. -1.  0.]] 

[65, 65, 23, 44, 1, 86, 65, 127, 44, 44, 107, 23, 23, 65, 23, 1, 44, 44, 44, 23, 1, 23, 86]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  

[38, 56, 74, 20, 20, 55, 1, 92, 38, 20, 56, 38, 38, 56, 20, 74, 74, 38, 74, 38]
[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0. -1.  0.  1. -1.]
 [-1.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]] 

[19, 53, 19, 53, 19, 19, 104, 53, 36, 36, 19, 19, 104, 69, 36, 19, 53, 87, 53]
[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0. -1.  0.  1. -1.]
 [-1.  1.  0.  0.  1.]
 [ 0.  0.  0.  0.  0.]] 

[18, 50, 18, 66, 49, 18, 1, 98, 34, 82, 50, 34, 66, 34, 81, 34, 49, 34]
[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0. -1.  0.  1. -1.]
 [-1.  1.  0.  0.  1.]
 [ 0. -1.  0.  0.  0.]] 

[62, 17, 77, 32, 32, 32, 1, 76, 62, 47, 62, 77, 32, 17, 62, 47, 32]
[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0. -1.  1.  1. -1.]
 [-1.  1.  0.  0.  1.]
 [ 0. -1.  0.  0.  0.]] 

[30, 44, 16, 16, 72, 58, 1, 86, 58, 30, 72, 30, 44, 58, 44, 58]
[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0. -1.  1.  1. -1.]
 [-1.  1. -1.  0.  1.]
 [ 0. -1.  0.  0.  0.]] 

[1, 67, 80, 67, 54, 54, 1, 1, 40, 92, 1, 1, 79,

[40, 1, 40, 21, 1, 1, 40, 59, 59, 40, 96, 40, 21, 78, 97, 21, 1, 97, 59, 78, 78]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  1. -1.  0.  0.]
 [-1.  0.  0.  1.  0.]
 [ 0.  1.  0.  0.  0.]] 

[1, 1, 55, 38, 56, 74, 38, 56, 56, 91, 56, 38, 38, 91, 20, 20, 56, 20, 74, 38]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  1. -1. -1.  0.]
 [-1.  0.  0.  1.  0.]
 [ 0.  1.  0.  0.  0.]] 

[70, 36, 70, 36, 19, 36, 36, 53, 103, 53, 70, 53, 1, 53, 36, 52, 36, 70, 1]
[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  1. -1. -1.  0.]
 [-1.  0.  0.  1.  0.]
 [ 0.  1.  0.  0.  0.]] 

[18, 112, 34, 1, 49, 50, 81, 50, 50, 66, 1, 66, 66, 34, 50, 1, 18, 66]
[[ 0.  0.  0.  0.  0.]
 [-1.  1.  0.  0.  0.]
 [ 0.  1. -1. -1.  0.]
 [-1.  0.  0.  1.  0.]
 [ 0.  1.  0.  0.  0.]] 

[62, 1, 47, 62, 32, 106, 61, 47, 77, 32, 1, 17, 32, 47, 32, 76, 32]
[[ 0.  0.  1.  0.  0.]
 [-1.  1.  0.  0.  0.]
 [ 0.  1. -1. -1.  0.]
 [-1.  0.  0.  1.  0.]
 [ 0.  1.  0.  0.  0.]] 

[30, 44, 72, 57, 72, 44, 1, 1, 1, 4

[40, 40, 40, 21, 40, 59, 59, 21, 116, 1, 1, 78, 40, 97, 40, 78, 59, 59, 1, 21, 59]
[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  1. -1.  0.  0.]
 [-1.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]] 

Game 24 Done 6 338
[94, 25, 48, 25, 48, 71, 25, 48, 48, 48, 48, 25, 48, 94, 48, 117, 94, 25, 25, 1, 48, 48, 25, 25, 25]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 

[1, 155, 24, 24, 1, 90, 46, 1, 68, 1, 24, 46, 24, 46, 46, 68, 24, 112, 24, 24, 68, 111, 90, 1]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0. -1.  0.]] 

[23, 1, 65, 23, 44, 65, 86, 44, 23, 44, 1, 44, 65, 44, 44, 107, 107, 23, 107, 44, 23, 44, 1]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0. -1.  0.]] 

[22, 62, 42, 42, 42, 22, 1, 22, 22, 22, 62, 22, 22, 62, 22, 62, 101, 82, 82, 62, 62, 81]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1. -1.]
 [ 0.  0.  1.  0.  0.]
 [ 0

[46, 68, 68, 1, 24, 24, 24, 1, 90, 90, 46, 46, 46, 68, 24, 46, 90, 46, 68, 1, 68, 24, 46, 68]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [-1.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]] 

[23, 1, 86, 44, 23, 86, 44, 65, 44, 44, 44, 65, 1, 23, 23, 44, 23, 65, 65, 86, 44, 65, 65]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [-1.  1.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.]] 

[42, 81, 1, 22, 82, 1, 81, 62, 22, 42, 42, 102, 42, 1, 62, 22, 22, 42, 121, 22, 62, 42]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [-1.  1.  0.  1.  0.]
 [ 0. -1.  0.  0.  0.]] 

[40, 21, 59, 59, 1, 21, 96, 59, 40, 40, 59, 170, 59, 21, 59, 1, 1, 40, 21, 59, 40]
[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [-1.  1.  0.  1.  0.]
 [ 0. -1.  0.  0.  0.]] 

[56, 38, 20, 56, 1, 56, 92, 1, 91, 74, 38, 38, 56, 1, 109, 91, 38, 20, 38, 1]
[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0. -1.  0.  0.  0.]
 [-1.  1.  0.  1.  0.]
 [

[69, 19, 53, 1, 70, 1, 1, 70, 19, 70, 70, 1, 36, 53, 36, 121, 36, 70, 70]
[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  1.  0.  0.]
 [ 0. -1.  0.  0. -1.]
 [-1.  1.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.]] 

[82, 50, 50, 1, 82, 66, 18, 18, 18, 34, 34, 18, 34, 98, 50, 49, 66, 50]
[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  1.  0.  0.]
 [ 0. -1.  0. -1. -1.]
 [-1.  1.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.]] 

[32, 76, 32, 1, 17, 1, 1, 77, 91, 1, 1, 1, 91, 77, 47, 121, 92]
[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  1.  0.  0.]
 [ 0. -1.  1. -1. -1.]
 [-1.  1.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.]] 

Game 34 Done 10 966
[48, 1, 140, 25, 25, 71, 48, 25, 25, 48, 94, 48, 1, 48, 48, 25, 48, 1, 71, 1, 1, 48, 71, 117, 94]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0.]] 

[46, 24, 24, 68, 46, 24, 1, 46, 90, 68, 46, 46, 24, 1, 112, 112, 46, 46, 68, 1, 24, 46, 24, 90]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [-1.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.]] 

[23, 65, 86

[77, 40, 59, 21, 40, 116, 78, 78, 1, 1, 78, 78, 40, 40, 21, 1, 21, 59, 97, 1, 40]
[[ 0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [-1.  1.  0.  1.  0.]
 [ 0.  0.  0. -1.  0.]] 

[38, 38, 20, 20, 38, 38, 56, 56, 38, 20, 74, 109, 92, 56, 20, 56, 56, 20, 38, 38]
[[ 0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0. -1.  0.  0.  0.]
 [-1.  1.  0.  1.  0.]
 [ 0.  0.  0. -1.  0.]] 

[70, 53, 53, 36, 87, 53, 53, 36, 36, 53, 36, 19, 70, 1, 36, 36, 19, 87, 36]
[[ 0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0. -1.  0.  0.  0.]
 [-1.  1.  1.  1.  0.]
 [ 0.  0.  0. -1.  0.]] 

Game 40 Done 8 575
[25, 48, 94, 25, 1, 139, 71, 48, 1, 48, 94, 48, 25, 117, 25, 25, 1, 25, 48, 48, 71, 25, 48, 25, 48]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 

[24, 46, 24, 46, 90, 68, 68, 46, 46, 68, 68, 24, 46, 24, 1, 46, 90, 68, 111, 46, 1, 46, 24, 1]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [-1.  1.  0.  0.  0.]
 [ 0.  

[41, 105, 54, 41, 41, 155, 28, 1, 1, 67, 54, 54, 1, 15, 1]
[[ 0.  0.  0.  0.  0.]
 [-1.  1.  0.  0.  0.]
 [ 0. -1.  0.  1.  1.]
 [-1.  1.  0.  0.  1.]
 [ 0. -1.  1. -1.  0.]] 

[74, 14, 118, 84, 38, 1, 14, 49, 1, 83, 1, 49, 26, 49]
[[ 0. -1.  0.  0.  0.]
 [-1.  1.  0.  0.  0.]
 [ 0. -1.  0.  1.  1.]
 [-1.  1.  0.  0.  1.]
 [ 0. -1.  1. -1.  0.]] 

[56, 78, 88, 57, 1, 67, 1, 1, 1, 140, 1, 56, 1]
[[ 0. -1.  0.  0.  0.]
 [-1.  1.  1.  0.  0.]
 [ 0. -1.  0.  1.  1.]
 [-1.  1.  0.  0.  1.]
 [ 0. -1.  1. -1.  0.]] 

Game 45 Done 14 1983
[48, 117, 25, 25, 25, 25, 25, 94, 71, 25, 71, 48, 1, 71, 25, 25, 71, 48, 25, 25, 94, 1, 48, 117, 25]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 

[1, 46, 46, 24, 68, 46, 24, 46, 68, 90, 24, 24, 1, 24, 46, 134, 112, 68, 46, 68, 1, 24, 46, 46]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [-1.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]] 

[44, 1, 44, 23, 23, 23, 44, 65, 86, 44, 23, 23, 65, 127

[82, 22, 1, 1, 22, 62, 62, 121, 42, 102, 62, 122, 1, 22, 42, 42, 1, 42, 1, 42, 102, 22]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [-1.  1.  0.  0.  0.]
 [ 0.  0.  1. -1.  0.]] 

[21, 40, 40, 1, 40, 40, 78, 59, 21, 40, 1, 78, 97, 21, 78, 78, 59, 78, 78, 21, 1]
[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [-1.  1.  0.  0.  0.]
 [ 0.  0.  1. -1.  0.]] 

[20, 91, 38, 38, 20, 1, 20, 20, 74, 56, 109, 74, 1, 110, 20, 38, 91, 20, 38, 38]
[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0. -1.  0.  0.  0.]
 [-1.  1.  0.  0.  0.]
 [ 0.  0.  1. -1.  0.]] 

[53, 19, 53, 19, 19, 70, 19, 53, 19, 1, 53, 69, 103, 53, 19, 36, 36, 102, 70]
[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0. -1.  0.  0.  0.]
 [-1.  1.  0.  0.  0.]
 [ 0.  1.  1. -1.  0.]] 

[34, 34, 98, 34, 66, 50, 1, 18, 34, 65, 18, 160, 82, 1, 82, 1, 34, 18]
[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0. -1.]
 [ 0. -1.  0.  0.  0.]
 [-1.  1.  0.  0.  0.]
 [ 0.  1.  1. -1.  0.]] 

[62, 1, 91

[18, 18, 50, 1, 66, 34, 50, 18, 50, 66, 82, 80, 50, 1, 34, 97, 34, 66]
[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  0.  1.  0.]
 [ 0. -1.  0.  0.  0.]
 [ 0.  1. -1.  0. -1.]
 [ 0.  0.  0. -1.  1.]] 

Game 5 Done 9 691
[48, 48, 71, 48, 25, 25, 25, 48, 71, 71, 48, 71, 1, 48, 48, 48, 25, 48, 94, 25, 48, 48, 25, 71, 48]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 

[24, 90, 24, 46, 1, 46, 1, 24, 68, 90, 46, 112, 24, 24, 68, 68, 24, 1, 1, 68, 24, 156, 68, 24]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -1.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]] 

no children
[1, 65, 23, 44, 44, 1, 107, 23, 1, 65, 65, 107, 65, 86, 1, 65, 44, 65, 65, 1, 86, 23, 23]
[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0. -1.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]] 

[61, 62, 101, 22, 42, 22, 22, 42, 42, 22, 22, 22, 140, 22, 42, 62, 42, 62, 42, 82, 1, 42]
[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0. -1.]
 [ 0.  0.  1.  0.  0.]
 [-1.  0

[68, 46, 46, 68, 46, 24, 46, 1, 24, 134, 46, 90, 24, 46, 90, 1, 24, 1, 24, 68, 24, 90, 68, 24]
[[ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [-1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]] 

[1, 44, 1, 23, 23, 86, 65, 65, 44, 23, 65, 1, 65, 65, 44, 44, 44, 44, 85, 44, 65, 85, 44]
[[ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [-1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]] 

[22, 62, 22, 22, 82, 42, 42, 22, 1, 42, 22, 62, 42, 62, 62, 102, 102, 22, 22, 62, 42, 82]
[[ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0. -1.  1.  0.  0.]
 [-1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]] 

no children
[96, 40, 21, 59, 21, 78, 1, 97, 40, 40, 1, 40, 21, 116, 59, 59, 21, 78, 21, 21, 40]
[[ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0. -1.  1.  0.  0.]
 [-1.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.]] 

[20, 74, 92, 38, 162, 56, 1, 20, 38, 1, 20, 20, 38, 20, 56, 20, 1, 56, 74, 110]
[[ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0. -1.]
 [ 0. -1.  1.  0.  0.]
 [-1.  0

[49, 50, 50, 26, 1, 50, 1, 85, 1, 1, 96, 38, 86, 74]
[[ 0.  1.  0.  0.  0.]
 [ 1.  1.  0.  1. -1.]
 [ 0. -1.  0. -1.  0.]
 [-1.  1.  0. -1.  0.]
 [ 0.  0.  1. -1.  0.]] 

Game 15 Done 13 1540
[48, 1, 71, 25, 48, 1, 93, 25, 25, 71, 71, 48, 1, 25, 71, 25, 48, 140, 48, 25, 48, 71, 25, 48, 71]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 

[1, 90, 68, 68, 24, 24, 1, 24, 90, 112, 24, 68, 24, 24, 24, 24, 24, 24, 46, 46, 68, 68, 89, 68]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -1.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]] 

no children
[65, 44, 65, 44, 44, 23, 86, 65, 65, 44, 65, 23, 44, 85, 23, 23, 1, 1, 65, 23, 65, 65, 44]
[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0. -1.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]] 

[22, 22, 22, 62, 62, 42, 22, 42, 22, 102, 62, 1, 22, 42, 82, 62, 62, 82, 22, 62, 82, 22]
[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0. -1.]
 [ 0.  0.  1.  0.  0.]
 [-1.  0.  0.  0.  0.]


Game 20 Done 10 894
[25, 25, 71, 48, 25, 117, 71, 25, 48, 48, 48, 48, 48, 94, 25, 71, 25, 1, 117, 48, 71, 25, 1, 25, 25]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 

[46, 67, 24, 46, 46, 1, 24, 46, 24, 177, 46, 90, 1, 90, 46, 24, 24, 24, 46, 46, 46, 24, 24, 90]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -1.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]] 

[65, 44, 23, 44, 23, 44, 128, 23, 23, 128, 1, 23, 23, 65, 44, 44, 86, 44, 1, 86, 44, 23, 44]
[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0. -1.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]] 

[22, 82, 62, 42, 22, 1, 22, 42, 22, 62, 102, 22, 81, 61, 82, 82, 62, 42, 81, 1, 1, 22]
[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0. -1.]
 [ 0.  0.  1.  0.  0.]
 [-1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]] 

[1, 21, 59, 40, 96, 97, 1, 59, 40, 78, 59, 21, 40, 115, 1, 21, 21, 97, 21, 78, 21]
[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0. -1.]
 [ 0.  0.  1.  0.  0.]
 [-1

[46, 35, 78, 24, 78, 1, 1, 87, 1, 56, 67, 56, 24]
[[ 0.  0.  1.  1.  0.]
 [ 1.  0.  0.  1.  1.]
 [ 0.  0. -1.  0. -1.]
 [-1.  1.  0. -1. -1.]
 [ 0.  0.  1. -1.  0.]] 

[50, 70, 99, 1, 40, 32, 97, 1, 1, 71, 41, 1]
[[ 0.  0.  1.  1.  0.]
 [ 1.  0.  0.  1.  1.]
 [ 0.  0. -1.  0. -1.]
 [-1.  1. -1. -1. -1.]
 [ 0.  0.  1. -1.  0.]] 

Game 24 Done 15 2094
[25, 117, 1, 71, 48, 94, 1, 1, 48, 25, 25, 71, 48, 48, 25, 71, 71, 1, 94, 25, 94, 1, 117, 48, 1]
[[0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 

[24, 24, 1, 90, 1, 24, 1, 24, 46, 46, 24, 68, 90, 1, 68, 68, 133, 46, 24, 24, 68, 90, 46, 90]
[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0. -1.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]] 

no children
[23, 44, 65, 1, 65, 86, 23, 44, 44, 23, 65, 86, 44, 23, 23, 23, 85, 65, 44, 23, 85, 65, 23]
[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0. -1.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]] 

[42, 22, 42, 81, 42, 42,

[1, 46, 89, 1, 111, 46, 111, 24, 112, 68, 68, 90, 1, 24, 68, 1, 1, 68, 46, 1, 1, 90, 24, 24]
[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0. -1.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]] 

no children
[65, 65, 86, 44, 65, 23, 23, 65, 44, 65, 1, 65, 1, 23, 23, 65, 65, 65, 44, 1, 86, 65, 23]
[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0. -1.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]] 

[22, 42, 22, 22, 22, 22, 22, 22, 42, 42, 22, 82, 22, 82, 82, 82, 42, 82, 62, 102, 62, 22]
[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0. -1.  0.  0.]
 [ 0.  1.  0.  0. -1.]
 [ 0.  0.  0.  0.  0.]] 

[59, 59, 40, 21, 40, 59, 21, 59, 21, 21, 1, 96, 78, 78, 59, 59, 1, 21, 97, 21, 59]
[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0. -1.  0.  0.]
 [ 0.  1.  0.  0. -1.]
 [ 0.  0.  1.  0.  0.]] 

[1, 38, 108, 74, 1, 74, 56, 20, 20, 74, 92, 1, 20, 38, 74, 20, 20, 1, 145, 38]
[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0. -1.  0.  0.]
 [ 0.  1.  0

[1, 96, 78, 21, 1, 21, 116, 21, 21, 59, 59, 116, 21, 21, 1, 97, 97, 40, 40, 40, 1]
[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0. -1.]
 [ 0.  0.  1.  0.  0.]
 [-1.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.]] 

Game 34 Done 6 450
[1, 25, 25, 25, 71, 71, 183, 25, 1, 94, 25, 1, 140, 71, 25, 25, 48, 1, 71, 25, 25, 71, 71, 25, 25]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 

[46, 68, 24, 46, 24, 1, 24, 24, 89, 24, 68, 68, 46, 133, 46, 67, 24, 46, 24, 24, 24, 46, 112, 24]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0. -1.  0.]] 

no children
[86, 1, 23, 44, 44, 65, 86, 23, 44, 23, 65, 44, 128, 44, 23, 23, 86, 1, 86, 1, 1, 1, 127]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0. -1.  0.]] 

[1, 62, 62, 82, 1, 102, 1, 102, 42, 22, 22, 42, 1, 62, 42, 1, 62, 42, 62, 62, 101, 42]
[[ 0.  0.  0.  0.  0.]
 [-1.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  

[56, 38, 92, 38, 56, 38, 56, 92, 38, 1, 38, 74, 38, 92, 38, 20, 20, 20, 38, 38]
[[ 0.  0.  0.  0.  0.]
 [ 1.  1.  0.  0. -1.]
 [ 0.  0.  1.  0.  0.]
 [-1.  0.  0.  0.  0.]
 [ 0.  0.  0. -1.  0.]] 

[1, 36, 137, 53, 52, 1, 19, 86, 70, 53, 87, 36, 53, 1, 53, 36, 69, 19, 1]
[[ 0.  0.  0.  0.  0.]
 [ 1.  1.  0.  0. -1.]
 [ 0.  0.  1.  0.  1.]
 [-1.  0.  0.  0.  0.]
 [ 0.  0.  0. -1.  0.]] 

[50, 34, 50, 34, 66, 18, 34, 82, 50, 50, 50, 18, 65, 18, 50, 18, 98, 34]
[[ 0.  0.  0.  0.  0.]
 [ 1.  1.  0.  0. -1.]
 [ 0.  0.  1.  0.  1.]
 [-1.  0.  0. -1.  0.]
 [ 0.  0.  0. -1.  0.]] 

[1, 62, 62, 17, 32, 1, 17, 17, 107, 1, 77, 122, 77, 17, 47, 62, 47]
[[ 0.  0.  0.  0.  0.]
 [ 1.  1.  0.  0. -1.]
 [ 0.  0.  1.  0.  1.]
 [-1.  0.  1. -1.  0.]
 [ 0.  0.  0. -1.  0.]] 

[86, 44, 16, 16, 44, 72, 44, 86, 44, 1, 30, 16, 58, 44, 30, 86]
[[ 0.  0.  0.  0.  0.]
 [ 1.  1.  0.  0. -1.]
 [ 0.  0.  1. -1.  1.]
 [-1.  0.  1. -1.  0.]
 [ 0.  0.  0. -1.  0.]] 

Game 39 Done 11 1307
[117, 71, 48, 71, 25, 48, 25, 

[22, 101, 82, 62, 1, 1, 62, 1, 42, 1, 42, 42, 62, 42, 22, 62, 102, 22, 82, 22, 82, 62]
[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0. -1.]
 [ 0.  0.  1.  0.  0.]
 [-1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]] 

[1, 77, 21, 97, 21, 116, 78, 40, 40, 21, 40, 77, 21, 40, 1, 59, 40, 97, 21, 21, 40]
[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0. -1.]
 [ 0.  0.  1.  0.  0.]
 [-1.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.]] 

Game 44 Done 6 398
[71, 48, 25, 1, 25, 1, 94, 48, 71, 25, 25, 25, 140, 71, 25, 71, 1, 117, 48, 25, 48, 48, 25, 48, 48]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 

[46, 68, 112, 24, 46, 24, 1, 1, 46, 68, 1, 24, 24, 90, 90, 46, 46, 1, 134, 46, 46, 68, 46, 24]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [-1.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]] 

no children
[86, 1, 107, 65, 65, 44, 1, 65, 65, 1, 23, 23, 1, 23, 44, 44, 65, 23, 23, 85, 86, 107, 23]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  

[23, 23, 44, 86, 23, 65, 65, 65, 65, 65, 65, 65, 44, 65, 65, 1, 44, 23, 44, 1, 44, 23, 65]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.]
 [ 0. -1.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]] 

[62, 1, 62, 42, 62, 42, 42, 22, 22, 22, 42, 42, 22, 142, 22, 42, 102, 62, 62, 22, 1, 82]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.]
 [ 0. -1.  0.  0.  0.]
 [-1.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]] 

[40, 1, 59, 59, 21, 78, 21, 40, 40, 135, 40, 21, 1, 40, 40, 59, 59, 78, 59, 40, 40]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.]
 [ 0. -1.  0.  0.  0.]
 [-1.  1.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.]] 

[20, 56, 20, 20, 56, 74, 74, 1, 56, 38, 20, 20, 56, 74, 38, 38, 128, 38, 56, 38]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.]
 [ 0. -1.  0.  0.  0.]
 [-1.  1.  0.  1. -1.]
 [ 0.  0.  0.  0.  0.]] 

[53, 19, 19, 36, 53, 19, 70, 19, 36, 69, 36, 53, 53, 1, 70, 70, 53, 53, 87]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.]
 [ 0. -1.  0.  0.  0.]
 [-1.  1.  0.  1. -1.]
 [ 0.  0.  0.  

[65, 44, 44, 44, 23, 44, 44, 44, 23, 44, 44, 23, 23, 44, 86, 23, 106, 127, 23, 23, 44, 44, 44]
[[ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0. -1.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]] 

[42, 61, 42, 62, 82, 42, 22, 1, 22, 42, 82, 102, 42, 22, 82, 1, 22, 62, 22, 102, 42, 22]
[[ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0. -1.  0.  0.]
 [ 0.  1.  0.  0. -1.]
 [ 0.  0.  0.  0.  0.]] 

[1, 96, 40, 21, 1, 21, 40, 21, 21, 78, 59, 40, 21, 21, 21, 40, 21, 97, 78, 96, 134]
[[ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0. -1.  0.  0.]
 [ 0.  1.  0.  0. -1.]
 [ 0.  0.  0.  1.  0.]] 

[92, 110, 56, 1, 38, 56, 38, 1, 20, 56, 56, 74, 74, 56, 38, 74, 20, 20, 20, 20]
[[ 0.  0.  1.  0.  0.]
 [-1.  0.  0.  0.  0.]
 [ 0.  0. -1.  0.  0.]
 [ 0.  1.  0.  0. -1.]
 [ 0.  0.  0.  1.  0.]] 

[53, 70, 19, 36, 103, 36, 19, 19, 70, 19, 36, 121, 19, 53, 19, 70, 19, 19, 69]
[[ 0.  0.  1.  0.  0.]
 [-1.  1.  0.  0.  0.]
 [ 0.  0. -1.  0.  0.]
 [ 0.  1.  0.  0. -1.]
 [ 0.  0.

[68, 46, 68, 68, 24, 24, 1, 68, 24, 24, 24, 1, 46, 46, 68, 90, 24, 133, 46, 68, 24, 112, 24, 1]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0. -1.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]] 

no children
[65, 44, 107, 23, 23, 65, 1, 1, 23, 44, 85, 1, 65, 23, 65, 65, 44, 64, 86, 23, 44, 65, 44]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  1.  0. -1.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]] 

[22, 22, 102, 42, 102, 22, 42, 42, 62, 62, 42, 42, 22, 22, 42, 42, 62, 22, 62, 42, 62, 42]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -1.]
 [ 0.  1.  0. -1.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]] 

no children
[1, 153, 116, 40, 1, 59, 1, 78, 59, 21, 78, 1, 59, 77, 59, 1, 59, 1, 40, 40, 21]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -1.]
 [ 0.  1.  0. -1.  0.]
 [ 0.  1.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.]] 

[38, 38, 20, 1, 92, 109, 1, 38, 73, 38, 92, 20, 20, 56, 38, 92, 74, 38, 38, 1]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0. -1.  0. -1.]
 [ 0.  1.  0. -1.  0

[40, 40, 97, 97, 21, 21, 1, 97, 21, 59, 40, 40, 59, 59, 21, 96, 59, 1, 40, 1, 59]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  1. -1.  0.  0.]
 [ 0.  1.  0.  0. -1.]
 [ 0.  0.  0.  0.  0.]] 

[20, 1, 20, 74, 92, 1, 56, 38, 56, 56, 109, 38, 38, 38, 74, 56, 56, 1, 20, 74]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [-1.  1. -1.  0.  0.]
 [ 0.  1.  0.  0. -1.]
 [ 0.  0.  0.  0.  0.]] 

[36, 121, 36, 1, 19, 69, 1, 19, 36, 87, 53, 1, 36, 102, 53, 1, 154, 36, 19]
[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  1.  0.  0.]
 [-1.  1. -1.  0.  0.]
 [ 0.  1.  0.  0. -1.]
 [ 0.  0.  0.  0.  0.]] 

Game 13 Done 8 738
[1, 48, 71, 71, 71, 25, 1, 93, 140, 25, 48, 117, 1, 1, 1, 48, 71, 94, 25, 25, 48, 48, 71, 1, 25]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 

[46, 68, 46, 46, 46, 24, 134, 68, 24, 1, 112, 24, 68, 46, 46, 1, 68, 90, 24, 1, 24, 46, 68, 1]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0. -1.

Game 18 Done 8 682
[48, 93, 116, 48, 25, 25, 48, 25, 48, 48, 25, 48, 25, 48, 71, 71, 70, 48, 1, 48, 25, 48, 25, 25, 71]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0.]] 

[24, 112, 68, 1, 112, 46, 46, 90, 46, 46, 46, 24, 153, 24, 1, 24, 24, 68, 24, 24, 24, 68, 1, 24]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0. -1.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.]] 

no children
[1, 44, 23, 23, 23, 44, 86, 44, 1, 86, 44, 44, 128, 86, 44, 64, 23, 44, 44, 65, 23, 44, 44]
[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  0. -1.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.]] 

[42, 22, 42, 22, 42, 22, 1, 82, 22, 42, 102, 22, 82, 42, 42, 42, 42, 62, 62, 121, 1, 62]
[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  0. -1.  0.]
 [ 0.  0. -1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.]] 

[40, 21, 21, 21, 21, 1, 78, 21, 40, 40, 1, 59, 59, 97, 96, 78, 21, 78, 59, 59, 59]
[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  0. -1.  0.]
 [ 0.  0. -1. 

[65, 23, 1, 86, 23, 85, 23, 86, 65, 65, 65, 44, 23, 44, 23, 44, 65, 86, 128, 1, 1, 1, 23]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 1.  0.  1. -1.  0.]] 

[82, 42, 42, 62, 42, 42, 42, 42, 62, 62, 121, 62, 42, 22, 42, 62, 42, 1, 1, 42, 22, 42]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0. -1.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 1.  0.  1. -1.  0.]] 

no children
[1, 40, 97, 40, 40, 40, 78, 21, 21, 40, 59, 40, 78, 21, 40, 40, 97, 78, 40, 1, 59]
[[ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0. -1.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 1.  0.  1. -1.  0.]] 

[20, 38, 74, 1, 56, 56, 92, 56, 20, 56, 74, 74, 20, 56, 38, 20, 1, 38, 74, 56]
[[ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0. -1.  0.  0.]
 [ 0.  0.  0.  0. -1.]
 [ 1.  0.  1. -1.  0.]] 

[36, 19, 104, 36, 36, 36, 53, 53, 53, 36, 53, 19, 70, 19, 53, 104, 69, 1, 19]
[[ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0. -1.  0.  0.]
 [ 0.  0.  1.  0. -1.]
 [ 1. 

[101, 22, 42, 62, 82, 42, 122, 42, 42, 22, 101, 22, 42, 22, 1, 62, 42, 22, 62, 42, 22, 1]
[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0. -1. -1.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.]] 

[78, 96, 21, 1, 97, 21, 21, 21, 59, 1, 40, 40, 21, 40, 78, 40, 78, 21, 59, 59, 78]
[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  1. -1. -1.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.]] 

[1, 20, 1, 20, 1, 128, 56, 92, 38, 109, 1, 1, 1, 74, 56, 20, 56, 56, 128, 55]
[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  1. -1. -1. -1.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.]] 

Game 28 Done 7 512
[1, 25, 25, 25, 1, 1, 48, 1, 71, 71, 94, 71, 1, 48, 48, 94, 117, 71, 1, 71, 1, 25, 71, 161, 25]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 

[46, 68, 1, 24, 46, 46, 68, 24, 90, 24, 24, 67, 24, 90, 46, 46, 1, 90, 24, 24, 134, 24, 24, 68]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0. -1.]

[65, 23, 1, 44, 1, 44, 44, 107, 107, 1, 86, 44, 1, 23, 44, 23, 44, 44, 1, 44, 86, 86, 106]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  1.  0.  0. -1.]
 [ 0.  0.  0.  0.  0.]] 

[62, 62, 62, 42, 82, 82, 42, 82, 62, 22, 42, 102, 22, 42, 1, 22, 22, 22, 1, 42, 22, 81]
[[ 0.  0.  0.  0.  0.]
 [ 0. -1.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  1.  0.  0. -1.]
 [ 0.  0.  0.  0.  0.]] 

[40, 97, 1, 40, 21, 59, 59, 59, 97, 40, 97, 1, 78, 1, 59, 59, 40, 1, 59, 21, 40]
[[ 0.  0.  0.  0.  0.]
 [ 0. -1.  1.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  1.  0.  0. -1.]
 [ 0.  0.  0.  0.  0.]] 

[38, 91, 128, 74, 20, 20, 38, 55, 56, 92, 56, 20, 38, 1, 38, 38, 38, 38, 20, 20]
[[ 0.  0.  0.  0.  0.]
 [-1. -1.  1.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  1.  0.  0. -1.]
 [ 0.  0.  0.  0.  0.]] 

[104, 70, 36, 1, 53, 87, 53, 1, 70, 19, 53, 1, 53, 87, 36, 1, 104, 1, 53]
[[ 0.  0.  0.  0.  0.]
 [-1. -1.  1.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  1.  0.  0. -1.]
 [ 0.  0.  1.  0.  0.

[1, 92, 56, 20, 20, 92, 20, 38, 20, 74, 20, 74, 92, 1, 56, 20, 38, 56, 56, 74]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0. -1.  0.  0.]
 [ 1.  1.  0.  0. -1.]
 [ 0.  0.  1. -1.  0.]] 

[86, 53, 70, 69, 19, 70, 36, 19, 1, 53, 1, 53, 19, 53, 1, 53, 53, 102, 70]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0. -1.  0.  0.]
 [ 1.  1.  1.  0. -1.]
 [ 0.  0.  1. -1.  0.]] 

Game 38 Done 8 603
[71, 94, 25, 25, 1, 117, 48, 94, 25, 117, 25, 48, 48, 25, 25, 48, 71, 48, 25, 25, 1, 94, 48, 25, 1]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0.]] 

[46, 46, 24, 46, 46, 46, 46, 24, 46, 90, 24, 1, 156, 1, 46, 90, 46, 46, 46, 46, 46, 46, 24, 46]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0. -1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.]] 

[44, 65, 1, 23, 65, 23, 23, 86, 44, 64, 65, 65, 23, 65, 44, 1, 44, 44, 23, 65, 65, 65, 65]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0. -1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 

[46, 111, 68, 24, 90, 68, 46, 24, 68, 24, 24, 68, 46, 111, 24, 1, 1, 24, 1, 46, 46, 46, 68, 46]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0. -1.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.]] 

[65, 23, 23, 44, 44, 44, 1, 65, 23, 44, 44, 86, 23, 86, 23, 65, 65, 44, 44, 65, 64, 44, 44]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  1.  0. -1.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.]] 

[62, 62, 81, 22, 1, 62, 82, 62, 121, 82, 42, 42, 1, 42, 1, 62, 22, 1, 82, 42, 22, 22]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [-1.  1.  0. -1.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.]] 

[1, 78, 78, 40, 59, 40, 59, 58, 21, 59, 116, 40, 1, 21, 59, 21, 59, 59, 21, 59, 21]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [-1.  1.  1. -1.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.]] 

[1, 56, 110, 20, 1, 20, 20, 56, 56, 74, 92, 56, 20, 38, 20, 20, 20, 74, 127, 38]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -1.]
 [-1.  1.  1. -1.  0.]
 [ 0.  0.  0.  1.  0

[1, 62, 1, 47, 62, 1, 1, 92, 62, 106, 62, 32, 77, 1, 77, 32, 47]
[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  1.  0.  0.]
 [ 0. -1.  1.  0.  0.]
 [ 0.  0. -1.  1.  0.]
 [-1.  0. -1.  1.  0.]] 

Game 47 Done 10 1104
[71, 25, 25, 93, 48, 48, 48, 48, 71, 48, 25, 25, 25, 25, 48, 93, 1, 117, 48, 1, 94, 25, 25, 25, 71]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 

[1, 178, 24, 68, 1, 46, 24, 46, 68, 24, 133, 46, 24, 68, 68, 46, 1, 24, 24, 46, 24, 24, 89, 24]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0. -1.]
 [ 0.  0.  0.  0.  0.]] 

no children
[23, 44, 106, 44, 44, 44, 64, 23, 23, 64, 23, 44, 23, 1, 1, 65, 128, 23, 44, 86, 65, 23, 65]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0. -1.]
 [ 0.  0.  1.  0.  0.]] 

[42, 1, 1, 42, 42, 22, 62, 42, 61, 62, 42, 102, 102, 62, 22, 22, 62, 22, 42, 1, 121, 42]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0. -1.  0.  0.]
 [ 0.  1

[42, 62, 22, 42, 62, 42, 82, 1, 62, 42, 62, 22, 42, 42, 62, 42, 1, 22, 42, 82, 82, 62]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -1.]
 [ 0.  0.  1.  0.  0.]
 [-1.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.]] 

[59, 59, 59, 1, 21, 40, 40, 1, 78, 21, 59, 134, 40, 59, 40, 40, 59, 21, 1, 116, 21]
[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0. -1.]
 [ 0.  0.  1.  0.  0.]
 [-1.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.]] 

[56, 38, 56, 20, 56, 38, 74, 20, 20, 56, 20, 38, 92, 38, 55, 74, 56, 20, 56, 38]
[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0. -1.]
 [ 0. -1.  1.  0.  0.]
 [-1.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.]] 

[1, 36, 70, 36, 19, 36, 1, 137, 70, 104, 53, 87, 1, 87, 36, 19, 1, 36, 36]
[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0. -1.]
 [ 0. -1.  1.  1.  0.]
 [-1.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.]] 

[65, 129, 50, 50, 49, 66, 1, 34, 50, 50, 50, 18, 66, 50, 18, 34, 1, 34]
[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0. -1.]
 [ 0. -1.  1.  1.  0.]
 [-1.  0.  1.  0.  0.]
 [ 0.  0. -1.  0.  0.]] 

[1, 92, 47,

[1, 38, 38, 20, 20, 1, 20, 109, 38, 109, 110, 20, 20, 38, 110, 38, 20, 38, 56, 74]
[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0. -1.]
 [ 0. -1.  1.  0.  0.]
 [-1.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.]] 

[1, 1, 36, 70, 104, 36, 1, 53, 1, 137, 1, 19, 1, 69, 87, 87, 1, 86, 70]
[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0. -1.]
 [ 0. -1.  1.  0.  0.]
 [-1.  1.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.]] 

[65, 18, 34, 50, 50, 50, 1, 50, 49, 34, 50, 97, 50, 66, 1, 18, 98, 34]
[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0. -1.]
 [ 0. -1.  1. -1.  0.]
 [-1.  1.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.]] 

[1, 76, 92, 32, 77, 134, 1, 1, 17, 92, 1, 121, 1, 77, 1, 17, 17]
[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0. -1.]
 [ 0. -1.  1. -1.  0.]
 [-1.  1.  1.  1.  0.]
 [ 0.  0.  0.  0.  0.]] 

Game 9 Done 10 1284
[1, 25, 48, 71, 25, 71, 93, 1, 94, 71, 25, 48, 116, 1, 25, 48, 94, 71, 139, 25, 1, 1, 25, 25, 25]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 

[68, 46, 46, 46, 46, 24, 9

[1, 19, 19, 1, 121, 19, 1, 87, 53, 36, 36, 104, 1, 36, 87, 104, 1, 119, 19]
[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0. -1.]
 [ 0. -1.  1.  1.  0.]
 [-1.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.]] 

[50, 96, 50, 81, 34, 18, 1, 65, 50, 34, 49, 34, 34, 50, 18, 34, 18, 98]
[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0. -1.]
 [ 0. -1.  1.  1.  0.]
 [-1.  0.  1.  0.  0.]
 [ 0.  0.  0. -1.  0.]] 

[1, 47, 32, 47, 135, 106, 1, 47, 32, 1, 77, 1, 92, 47, 1, 1, 91]
[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0. -1.]
 [ 0. -1.  1.  1.  0.]
 [-1.  1.  1.  0.  0.]
 [ 0.  0.  0. -1.  0.]] 

[43, 1, 16, 71, 44, 85, 1, 86, 30, 58, 30, 44, 30, 126, 44, 1]
[[ 0. -1.  0.  0.  0.]
 [ 0.  1.  0.  0. -1.]
 [ 0. -1.  1.  1.  0.]
 [-1.  1.  1.  0.  0.]
 [ 0.  0.  0. -1.  0.]] 

[1, 80, 105, 80, 28, 1, 1, 80, 1, 1, 91, 1, 1, 1, 178]
[[ 0. -1.  0.  0.  0.]
 [ 0.  1.  0.  0. -1.]
 [ 0. -1.  1.  1.  0.]
 [-1.  1.  1.  1.  0.]
 [ 0.  0.  0. -1.  0.]] 

Game 15 Done 12 1914
[48, 71, 25, 1, 25, 48, 116, 1, 48, 48, 1, 1, 71, 94, 71, 

[114, 40, 59, 78, 40, 59, 1, 77, 115, 40, 21, 78, 1, 21, 59, 59, 59, 1, 40, 1, 1]
[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0. -1.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0. -1.  0.  0.]] 

Game 20 Done 6 432
[25, 48, 48, 48, 1, 25, 94, 1, 71, 48, 48, 94, 140, 1, 25, 48, 25, 1, 71, 1, 71, 71, 48, 48, 71]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 

[24, 112, 112, 90, 1, 68, 1, 24, 46, 68, 68, 46, 46, 89, 46, 24, 1, 46, 24, 90, 1, 68, 24, 1]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -1.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]] 

[23, 44, 65, 107, 44, 23, 65, 65, 65, 44, 44, 23, 23, 65, 1, 128, 65, 1, 44, 85, 44, 1, 1]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1. -1.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]] 

[22, 22, 22, 141, 42, 42, 62, 62, 22, 1, 42, 1, 42, 62, 22, 22, 42, 122, 42, 82, 100, 1]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1. -1.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0

[78, 59, 21, 59, 1, 154, 97, 78, 59, 59, 40, 21, 1, 77, 40, 1, 21, 21, 1, 59, 21]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1. -1.]
 [ 0.  0.  1.  0.  0.]
 [-1.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]] 

Game 26 Done 6 431
[48, 48, 48, 1, 94, 71, 25, 1, 94, 48, 94, 1, 162, 25, 94, 25, 48, 25, 25, 25, 48, 48, 25, 48, 1]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 

[24, 111, 24, 68, 24, 1, 46, 68, 68, 24, 68, 1, 68, 24, 154, 1, 46, 90, 46, 24, 24, 68, 24, 24]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -1.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]] 

[44, 65, 65, 23, 64, 44, 107, 23, 86, 107, 65, 23, 1, 65, 23, 23, 86, 23, 1, 1, 65, 23, 65]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -1.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.]] 

[82, 62, 22, 62, 42, 22, 102, 22, 42, 42, 122, 22, 42, 22, 22, 22, 42, 42, 42, 42, 62, 42]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -1.]
 [ 0.  0.  1.  0.  0.]
 [-1. 

[22, 1, 82, 42, 42, 22, 22, 42, 102, 82, 62, 22, 22, 62, 62, 62, 62, 42, 22, 42, 62, 42]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -1.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0. -1.  0.  0.]] 

[21, 1, 21, 58, 40, 59, 1, 40, 40, 96, 40, 40, 21, 40, 152, 21, 21, 78, 97, 78, 1]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1. -1.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0. -1.  0.  0.]] 

[1, 38, 20, 20, 1, 56, 38, 38, 74, 91, 91, 38, 128, 74, 38, 38, 20, 38, 38, 38]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1. -1.]
 [ 0.  0.  1. -1.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0. -1.  0.  0.]] 

[87, 53, 53, 103, 1, 87, 1, 121, 53, 36, 19, 19, 1, 19, 19, 36, 53, 102, 1]
[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  0.  1. -1.]
 [ 0.  0.  1. -1.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0. -1.  0.  0.]] 

Game 32 Done 8 794
[71, 25, 25, 25, 48, 25, 94, 1, 48, 1, 25, 1, 94, 1, 1, 48, 48, 25, 25, 94, 94, 71, 93, 117, 71]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0

[25, 48, 94, 1, 48, 1, 71, 48, 117, 71, 25, 71, 25, 25, 71, 71, 48, 48, 25, 25, 25, 25, 94, 48, 25]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 

[68, 90, 68, 68, 1, 46, 24, 1, 24, 68, 24, 68, 24, 46, 46, 46, 46, 112, 68, 24, 24, 24, 46, 68]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -1.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]] 

[65, 23, 23, 23, 65, 44, 65, 86, 86, 23, 23, 86, 65, 23, 23, 1, 65, 65, 23, 44, 44, 65, 44]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -1.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.]] 

[22, 42, 42, 22, 42, 1, 82, 62, 82, 62, 1, 62, 42, 102, 42, 22, 62, 82, 62, 22, 42, 22]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -1.]
 [ 0.  0.  1.  0.  0.]
 [-1.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.]] 

no children
[40, 40, 78, 97, 21, 40, 115, 1, 59, 21, 58, 40, 78, 59, 77, 21, 21, 21, 1, 40, 40]
[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0. -1.]
 [ 0.  0.  1.  0.  0.]
 [-1.  0.  1

Game 42 Done 12 1912
[25, 48, 138, 25, 48, 1, 71, 1, 25, 48, 48, 25, 94, 1, 25, 139, 70, 48, 48, 48, 25, 48, 71, 25, 25]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 

[46, 46, 24, 68, 1, 68, 46, 68, 90, 112, 24, 46, 1, 46, 24, 68, 24, 24, 1, 68, 112, 90, 1, 24]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -1.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]] 

[1, 23, 86, 86, 44, 23, 23, 86, 65, 23, 44, 86, 23, 65, 65, 44, 65, 23, 23, 23, 65, 65, 23]
[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0. -1.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]] 

[22, 61, 22, 62, 42, 42, 42, 82, 42, 22, 62, 82, 82, 22, 1, 22, 22, 42, 42, 101, 82, 22]
[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0. -1.]
 [ 0.  0.  1.  0.  0.]
 [-1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]] 

[1, 96, 59, 21, 21, 40, 59, 59, 1, 78, 115, 40, 97, 77, 1, 1, 1, 59, 59, 78, 1]
[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0. -1.]
 [ 0.  0.  1.  0.  0.]
 [-1.  

[78, 40, 59, 59, 96, 21, 1, 1, 40, 59, 78, 134, 40, 21, 40, 21, 1, 40, 59, 78, 1]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1. -1.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0. -1.  0.  0.]] 

[56, 128, 20, 20, 74, 1, 38, 56, 38, 38, 20, 38, 38, 56, 20, 1, 56, 110, 73, 38]
[[ 0.  0. -1.  0.  0.]
 [ 0.  0.  0.  1. -1.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0. -1.  0.  0.]] 

[36, 70, 36, 1, 86, 1, 87, 53, 104, 1, 36, 70, 1, 19, 87, 52, 36, 87, 1]
[[ 0.  0. -1.  0.  0.]
 [ 0.  1.  0.  1. -1.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0. -1.  0.  0.]] 

Game 48 Done 8 832
[117, 25, 25, 25, 94, 71, 25, 1, 71, 94, 48, 71, 117, 1, 25, 25, 1, 94, 71, 48, 1, 48, 48, 1, 25]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 

[46, 46, 90, 134, 1, 68, 24, 24, 1, 46, 46, 90, 1, 46, 68, 46, 46, 89, 46, 90, 24, 24, 24, 1]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -1.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0. 

[38, 20, 109, 56, 74, 20, 74, 74, 20, 38, 56, 55, 38, 38, 56, 1, 74, 20, 56, 20]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -1.]
 [ 0.  0.  1.  0.  0.]
 [-1.  0.  0. -1.  0.]
 [ 0.  0.  1.  1.  0.]] 

[36, 70, 70, 104, 36, 19, 87, 1, 53, 53, 36, 70, 36, 53, 1, 86, 68, 1, 1]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -1.]
 [ 0.  0.  1.  0.  0.]
 [-1.  0.  0. -1.  0.]
 [ 0.  1.  1.  1.  0.]] 

Game 2 Done 8 674
[94, 71, 25, 25, 1, 1, 48, 25, 71, 48, 71, 48, 116, 48, 25, 48, 71, 1, 117, 25, 1, 71, 25, 94, 1]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 

[68, 68, 46, 46, 24, 46, 68, 1, 133, 46, 24, 46, 24, 68, 46, 24, 68, 24, 1, 112, 1, 46, 46, 46]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -1.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]] 

[86, 23, 1, 23, 65, 44, 44, 86, 44, 1, 23, 44, 23, 23, 128, 1, 65, 44, 65, 107, 44, 23, 65]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -1.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [

[34, 66, 50, 65, 18, 1, 82, 18, 34, 50, 34, 18, 18, 66, 65, 98, 50, 50]
[[ 0.  0.  0.  0.  0.]
 [ 0. -1.  1. -1. -1.]
 [-1.  0.  1.  1.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.]] 

[76, 1, 1, 77, 77, 92, 1, 1, 91, 62, 1, 1, 107, 62, 105, 1, 1]
[[ 0.  0.  0.  0.  0.]
 [ 0. -1.  1. -1. -1.]
 [-1.  0.  1.  1.  0.]
 [ 0.  1.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.]] 

[58, 58, 1, 85, 57, 71, 58, 16, 44, 44, 1, 44, 16, 85, 30, 43]
[[ 0.  0.  0.  0.  0.]
 [ 0. -1.  1. -1. -1.]
 [-1.  0.  1.  1. -1.]
 [ 0.  1.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.]] 

[105, 1, 1, 141, 92, 93, 1, 41, 1, 1, 1, 104, 66, 1, 1]
[[ 0.  1.  0.  0.  0.]
 [ 0. -1.  1. -1. -1.]
 [-1.  0.  1.  1. -1.]
 [ 0.  1.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.]] 

Game 7 Done 12 1976
[71, 48, 25, 25, 94, 48, 48, 71, 71, 1, 25, 48, 71, 48, 117, 25, 1, 70, 71, 48, 71, 48, 25, 1, 1]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 

[46, 112, 68, 46, 1, 1, 46, 68, 24, 46, 24, 90, 112, 46, 67, 24

[21, 40, 21, 21, 59, 40, 78, 1, 59, 40, 40, 59, 97, 40, 21, 154, 78, 21, 1, 40, 40]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  1. -1.  0.]
 [ 0.  0.  1. -1.  0.]
 [ 0.  0.  1.  0.  0.]] 

Game 12 Done 6 440
[48, 71, 25, 25, 93, 48, 71, 1, 94, 25, 48, 1, 71, 93, 71, 1, 71, 1, 71, 25, 1, 48, 71, 93, 1]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 

[68, 112, 68, 46, 67, 1, 90, 68, 68, 46, 24, 24, 1, 68, 1, 1, 46, 46, 24, 46, 46, 46, 46, 68]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0. -1.  0.  0.]] 

[23, 44, 1, 23, 23, 65, 65, 1, 65, 128, 1, 23, 23, 44, 1, 86, 148, 148, 1, 44, 23, 1, 86]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0. -1.  0.  0.]] 

[22, 120, 22, 42, 42, 61, 42, 121, 42, 62, 1, 42, 42, 22, 42, 62, 1, 42, 1, 62, 62, 62]
[[ 0.  0.  0. -1.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0. 

[1, 46, 1, 68, 68, 24, 133, 46, 1, 68, 1, 24, 24, 68, 134, 46, 24, 68, 24, 24, 46, 46, 111, 24]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0. -1.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]] 

[1, 86, 86, 23, 86, 65, 23, 23, 44, 65, 65, 1, 1, 1, 65, 149, 65, 44, 23, 44, 44, 44, 23]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0. -1.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]] 

[22, 22, 62, 22, 42, 22, 82, 62, 42, 42, 62, 62, 22, 42, 82, 82, 22, 82, 42, 42, 22, 42]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0. -1.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0. -1.  0.  0.]] 

[97, 59, 21, 21, 59, 1, 133, 1, 97, 21, 21, 59, 40, 59, 40, 59, 40, 1, 78, 21, 40]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0. -1.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  1.  0.  1.  0.]
 [ 0.  0. -1.  0.  0.]] 

[20, 38, 38, 56, 20, 38, 74, 38, 20, 38, 92, 92, 72, 1, 56, 56, 1, 20, 109, 38]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0. -1.  0.  0.]
 [ 0.  0.  1.  0. -1.]
 [ 0.  1.  0.  1.  0.

[56, 56, 38, 56, 38, 74, 110, 20, 1, 56, 74, 38, 38, 20, 38, 38, 74, 20, 38, 38]
[[ 0.  0. -1.  0.  0.]
 [ 0. -1.  0.  0.  0.]
 [-1.  0.  1.  1.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.]] 

Game 23 Done 7 676
[25, 48, 25, 25, 117, 25, 48, 25, 48, 48, 48, 48, 71, 71, 25, 48, 71, 25, 48, 48, 71, 48, 71, 25, 25]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 

[68, 134, 90, 46, 46, 46, 24, 46, 1, 46, 1, 46, 46, 67, 68, 68, 67, 24, 46, 1, 24, 90, 24, 1]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0. -1.  0.]
 [ 0.  0.  0.  0.  0.]] 

[65, 23, 44, 44, 65, 44, 23, 23, 65, 65, 1, 23, 23, 86, 23, 107, 44, 44, 23, 128, 44, 44, 23]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0. -1.  0.]
 [ 0.  0.  1.  0.  0.]] 

[22, 42, 22, 62, 22, 22, 22, 42, 82, 82, 102, 82, 22, 22, 42, 22, 82, 22, 82, 22, 82, 22]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [-1

[78, 40, 1, 59, 59, 40, 40, 1, 59, 40, 40, 97, 21, 21, 40, 115, 95, 1, 21, 59, 40]
[[ 0.  0. -1.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  1.  0.  1.  0.]
 [ 0.  0. -1.  0.  0.]] 

[74, 38, 56, 74, 38, 38, 1, 74, 56, 20, 56, 91, 38, 56, 20, 91, 56, 1, 1, 38]
[[ 0.  0. -1.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0. -1.]
 [ 0.  1.  0.  1.  0.]
 [ 0.  0. -1.  0.  0.]] 

[86, 70, 36, 53, 121, 1, 103, 1, 36, 53, 19, 70, 36, 1, 36, 1, 53, 87, 1]
[[ 0.  0. -1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  1.  0. -1.]
 [ 0.  1.  0.  1.  0.]
 [ 0.  0. -1.  0.  0.]] 

Game 28 Done 8 846
[25, 48, 93, 1, 48, 48, 71, 48, 48, 25, 25, 48, 162, 70, 25, 71, 48, 48, 71, 25, 48, 1, 25, 48, 1]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 

[46, 46, 24, 1, 24, 68, 68, 46, 68, 68, 46, 24, 46, 24, 112, 68, 24, 24, 24, 46, 68, 68, 24, 68]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0. -1.  0.]
 [ 0.  0.  

[1, 46, 24, 46, 68, 46, 46, 90, 90, 24, 90, 24, 24, 24, 68, 24, 90, 24, 90, 24, 24, 46, 68, 24]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0. -1.  0.]
 [ 0.  0.  0.  0.  0.]] 

[44, 86, 44, 1, 23, 65, 44, 65, 65, 23, 86, 86, 1, 44, 1, 23, 1, 23, 86, 65, 148, 1, 44]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  1. -1.  0.]
 [ 0.  0.  0.  0.  0.]] 

[42, 82, 62, 62, 22, 82, 22, 1, 22, 42, 82, 1, 42, 62, 62, 62, 42, 62, 22, 22, 82, 42]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  1. -1.  0.]
 [ 0.  0.  1. -1.  0.]
 [ 0.  0.  0.  0.  0.]] 

no children
[1, 1, 40, 59, 40, 21, 96, 1, 134, 40, 40, 78, 78, 59, 59, 21, 59, 59, 1, 59, 21]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  1. -1.  0.]
 [ 0.  0.  1. -1.  0.]
 [ 0.  0.  1.  0.  0.]] 

Game 34 Done 6 451
[138, 71, 25, 25, 25, 25, 71, 25, 48, 25, 71, 48, 25, 25, 94, 48, 94, 1, 48, 25, 25, 25, 117, 25, 25]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 

[74, 38, 20, 74, 74, 56, 74, 74, 38, 20, 20, 56, 38, 73, 38, 38, 56, 20, 20, 20]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0. -1.  1.  0.  1.]
 [-1.  0.  1. -1.  0.]
 [ 0.  0.  0.  0.  0.]] 

[36, 36, 87, 70, 86, 70, 70, 1, 19, 36, 36, 1, 87, 104, 1, 36, 1, 70, 19]
[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0. -1.  1.  0.  1.]
 [-1.  0.  1. -1.  0.]
 [ 0.  0.  0.  0.  0.]] 

[1, 34, 50, 34, 50, 18, 1, 96, 50, 18, 113, 34, 50, 34, 50, 81, 66, 34]
[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0. -1.]
 [ 0. -1.  1.  0.  1.]
 [-1.  0.  1. -1.  0.]
 [ 0.  0.  0.  0.  0.]] 

[1, 92, 61, 62, 46, 47, 1, 47, 47, 1, 62, 77, 32, 17, 1, 62, 105]
[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0. -1.]
 [ 0. -1.  1.  0.  1.]
 [-1.  0.  1. -1.  0.]
 [ 0.  0.  1.  0.  0.]] 

Game 40 Done 10 1142
[48, 25, 48, 25, 25, 1, 71, 48, 1, 1, 71, 71, 71, 71, 48, 94, 25, 48, 94, 94, 25, 48, 71, 1, 48]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 

[112, 46, 24, 90, 1, 24,

[38, 38, 38, 20, 20, 56, 91, 73, 20, 20, 74, 20, 74, 56, 38, 38, 92, 56, 20, 38]
[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0. -1.  1.  0.  0.]
 [-1.  0.  0. -1.  0.]
 [ 0.  0.  1.  0.  0.]] 

[1, 19, 53, 70, 1, 53, 19, 1, 87, 53, 53, 87, 70, 1, 53, 36, 52, 87, 70]
[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0. -1.  1.  0.  0.]
 [-1.  0.  1. -1.  0.]
 [ 0.  0.  1.  0.  0.]] 

Game 45 Done 8 646
[71, 48, 25, 25, 70, 1, 48, 94, 48, 93, 25, 25, 93, 25, 1, 25, 94, 25, 94, 71, 71, 1, 48, 25, 25]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 

[24, 111, 46, 24, 24, 24, 24, 68, 24, 46, 46, 68, 68, 46, 1, 90, 1, 68, 46, 46, 46, 46, 24, 112]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0. -1.  0.]
 [ 0.  0.  0.  0.  0.]] 

[1, 86, 23, 23, 23, 44, 23, 23, 44, 65, 86, 44, 44, 23, 65, 23, 23, 1, 86, 86, 127, 86, 23]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  1. -1.  0.]
 

[1, 23, 106, 65, 44, 23, 1, 23, 1, 65, 1, 23, 86, 86, 44, 107, 86, 106, 23, 65, 23, 44, 23]
[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0. -1.  0.  0.]] 

[1, 42, 1, 1, 42, 62, 62, 42, 122, 62, 1, 62, 22, 42, 82, 62, 102, 1, 22, 102, 62, 42]
[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  0. -1.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0. -1.  0.  0.]] 

no children
[1, 134, 21, 40, 21, 59, 78, 40, 21, 40, 40, 59, 78, 59, 59, 1, 59, 21, 40, 40, 59]
[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  0. -1.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0. -1.  0.  0.]] 

[56, 20, 38, 92, 38, 20, 74, 1, 1, 38, 56, 38, 56, 73, 74, 92, 20, 56, 38, 38]
[[ 0.  0.  0.  0.  0.]
 [ 0.  1. -1. -1.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0. -1.  0.  0.]] 

[1, 53, 1, 53, 121, 86, 87, 53, 1, 19, 36, 53, 104, 1, 86, 1, 36, 70, 1]
[[ 0.  0.  0.  0.  0.]
 [ 0.  1. -1. -1.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  1.  0.  0.  1.]
 [ 0.  0.

[1, 42, 42, 1, 62, 22, 42, 101, 42, 82, 22, 1, 42, 1, 102, 82, 42, 42, 82, 42, 62, 62]
[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0. -1.  0.]
 [ 0.  0. -1.  0.  0.]] 

[1, 40, 78, 21, 40, 1, 78, 59, 40, 21, 21, 116, 21, 59, 78, 78, 40, 21, 40, 78, 40]
[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  1.  0. -1.  0.]
 [ 0.  0. -1.  0.  0.]] 

[74, 38, 109, 38, 20, 38, 38, 38, 73, 38, 20, 20, 1, 38, 38, 92, 20, 92, 20, 74]
[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  1.  0. -1.  0.]
 [ 0. -1. -1.  0.  0.]] 

[1, 86, 53, 36, 70, 36, 87, 1, 86, 19, 1, 70, 36, 53, 70, 87, 1, 36, 36]
[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  0.  1.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  1.  0. -1.  0.]
 [ 0. -1. -1.  0.  0.]] 

Game 6 Done 8 851
[1, 48, 48, 48, 25, 1, 139, 48, 48, 48, 48, 1, 140, 25, 1, 25, 71, 1, 25, 71, 71, 70, 94, 48, 25]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0

[34, 50, 50, 50, 18, 18, 1, 34, 18, 65, 50, 34, 34, 66, 50, 114, 34, 97]
[[ 0.  0.  0.  0.  0.]
 [ 0.  1. -1. -1. -1.]
 [ 0.  1.  1.  0.  1.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0. -1.  0.  0.]] 

Game 11 Done 9 1095
[71, 1, 71, 48, 48, 71, 48, 48, 48, 25, 71, 25, 93, 25, 25, 94, 94, 1, 94, 48, 1, 71, 1, 25, 25]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 

[24, 24, 24, 1, 1, 68, 112, 46, 24, 24, 68, 46, 68, 46, 46, 112, 1, 68, 24, 46, 46, 68, 68, 68]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0. -1.  0.  0.]] 

[65, 107, 23, 1, 23, 86, 23, 44, 44, 65, 65, 44, 23, 23, 65, 44, 44, 23, 65, 23, 86, 44, 44]
[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0. -1.  0.  0.]] 

[1, 100, 22, 62, 42, 62, 120, 62, 22, 42, 82, 1, 42, 42, 62, 22, 22, 62, 1, 42, 42, 62]
[[ 0.  0.  0.  0.  0.]
 [ 0.  1. -1.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.

[62, 82, 22, 62, 62, 42, 82, 1, 42, 22, 42, 62, 42, 62, 82, 22, 22, 81, 1, 62, 42, 22]
[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  0. -1.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0. -1.  0.  0.]] 

[1, 78, 78, 40, 59, 1, 21, 59, 96, 40, 40, 40, 40, 40, 1, 1, 40, 97, 135, 40, 21]
[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  0. -1.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0. -1.  0.  0.]] 

Game 17 Done 6 422
[1, 94, 48, 48, 71, 71, 117, 25, 25, 25, 25, 1, 48, 94, 48, 25, 48, 1, 48, 94, 48, 1, 25, 71, 71]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 

[24, 46, 46, 68, 1, 46, 68, 134, 46, 46, 24, 1, 46, 46, 46, 67, 24, 68, 68, 24, 112, 24, 24, 24]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0. -1.  0.  0.]] 

[44, 23, 44, 86, 1, 44, 65, 44, 44, 23, 44, 1, 44, 86, 1, 65, 107, 65, 107, 44, 23, 1, 65]
[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0. 

[24, 1, 112, 1, 68, 1, 24, 46, 68, 68, 24, 46, 1, 24, 46, 68, 46, 1, 46, 134, 46, 90, 46, 89]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0. -1.  0.  0.]] 

[44, 44, 1, 44, 23, 65, 65, 23, 44, 85, 65, 65, 1, 1, 23, 44, 44, 65, 23, 86, 65, 65, 86]
[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0. -1.  0.  0.]] 

[42, 62, 22, 42, 1, 42, 101, 62, 62, 42, 42, 22, 42, 42, 42, 82, 62, 1, 42, 42, 62, 62]
[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  0. -1.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0. -1.  0.  0.]] 

[1, 78, 40, 134, 1, 59, 40, 40, 21, 1, 21, 21, 40, 97, 59, 1, 59, 115, 96, 21, 21]
[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  0. -1.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0. -1.  0.  0.]] 

[20, 38, 20, 56, 74, 56, 92, 1, 20, 74, 1, 38, 20, 91, 110, 38, 56, 38, 20, 56]
[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  0. -1.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  1.  0. -1.  0.]
 

[86, 23, 44, 44, 1, 44, 106, 85, 44, 23, 23, 44, 1, 44, 44, 107, 65, 23, 86, 23, 23, 44, 44]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0. -1.  0.  0.]] 

[42, 82, 22, 1, 22, 22, 122, 62, 22, 62, 42, 42, 22, 42, 42, 22, 61, 62, 62, 42, 62, 82]
[[ 0.  0.  0.  0.  0.]
 [ 0. -1.  0.  1.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0. -1.  0.  0.]] 

[40, 40, 40, 1, 1, 116, 134, 59, 40, 78, 40, 40, 78, 1, 21, 21, 59, 59, 21, 78, 1]
[[ 0.  0.  0.  0.  0.]
 [ 0. -1.  1.  1.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0. -1.  0.  0.]] 

[38, 56, 38, 56, 1, 92, 20, 20, 74, 145, 38, 56, 38, 20, 74, 20, 20, 20, 109, 1]
[[ 0.  0.  0.  0.  0.]
 [ 0. -1.  1.  1.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0. -1.  0. -1.]] 

[53, 36, 1, 19, 1, 86, 1, 70, 36, 36, 103, 53, 1, 1, 87, 19, 36, 120, 103]
[[ 0.  0.  0.  0.  0.]
 [ 0. -1.  1.  1.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0. -1.  

[1, 40, 40, 59, 1, 21, 59, 59, 78, 59, 21, 40, 21, 40, 59, 59, 59, 59, 59, 1, 135]
[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [-1.  1.  1.  0.  0.]
 [ 0.  0.  0. -1.  0.]
 [ 0.  0.  0.  0.  0.]] 

[1, 38, 1, 20, 38, 38, 38, 110, 20, 74, 91, 38, 38, 38, 56, 74, 74, 20, 74, 38]
[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  0. -1.  0.]
 [-1.  1.  1.  0.  0.]
 [ 0.  0.  0. -1.  0.]
 [ 0.  0.  0.  0.  0.]] 

[1, 1, 53, 86, 36, 102, 53, 53, 1, 53, 53, 1, 36, 87, 53, 104, 53, 36, 1]
[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  0. -1.  0.]
 [-1.  1.  1.  0.  0.]
 [ 0.  1.  0. -1.  0.]
 [ 0.  0.  0.  0.  0.]] 

Game 32 Done 8 748
[48, 25, 48, 71, 1, 25, 71, 25, 71, 48, 25, 25, 161, 25, 25, 48, 117, 25, 48, 25, 48, 71, 1, 94, 1]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 

[1, 68, 24, 46, 46, 68, 90, 1, 46, 68, 46, 112, 24, 46, 24, 46, 46, 46, 24, 46, 24, 112, 68, 1]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.

[50, 34, 66, 34, 18, 81, 66, 34, 66, 66, 1, 1, 82, 34, 18, 34, 49, 97]
[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  0. -1.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  1.  0. -1.  1.]
 [ 0. -1. -1.  0.  0.]] 

[1, 32, 47, 17, 47, 17, 17, 91, 62, 1, 77, 106, 92, 77, 1, 47, 32]
[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  0. -1.  0.]
 [ 0.  0.  1.  0.  1.]
 [ 0.  1.  0. -1.  1.]
 [ 0. -1. -1.  0.  0.]] 

[44, 72, 85, 99, 44, 16, 1, 71, 30, 16, 1, 153, 72, 1, 1, 16]
[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  0. -1.  0.]
 [ 0.  0.  1.  0.  1.]
 [ 0.  1.  0. -1.  1.]
 [ 0. -1. -1. -1.  0.]] 

Game 37 Done 11 1486
[25, 25, 1, 48, 25, 48, 71, 48, 117, 1, 1, 48, 117, 25, 93, 25, 94, 1, 71, 1, 48, 115, 25, 1, 94]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 

[46, 24, 24, 24, 24, 46, 46, 111, 68, 24, 24, 46, 24, 24, 24, 24, 68, 112, 46, 46, 46, 68, 68, 68]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0. -1.  0.  0.]] 

[1, 23, 107, 65, 

[74, 56, 38, 20, 56, 1, 74, 20, 38, 20, 20, 20, 56, 20, 92, 74, 56, 56, 110, 20]
[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  0. -1.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  1.  0. -1.  0.]
 [ 0.  0. -1.  0.  0.]] 

[1, 87, 53, 36, 86, 19, 19, 1, 53, 1, 19, 36, 87, 86, 36, 1, 70, 136, 36]
[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  0. -1.  0.]
 [ 0.  0.  1.  0.  1.]
 [ 0.  1.  0. -1.  0.]
 [ 0.  0. -1.  0.  0.]] 

[18, 50, 34, 18, 66, 18, 81, 50, 18, 18, 1, 98, 50, 96, 66, 18, 66, 50]
[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  0. -1.  0.]
 [ 0.  0.  1.  0.  1.]
 [ 0.  1.  0. -1.  0.]
 [ 0. -1. -1.  0.  0.]] 

[1, 61, 17, 62, 122, 92, 91, 32, 62, 1, 1, 32, 90, 32, 1, 47, 17]
[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  0. -1.  1.]
 [ 0.  0.  1.  0.  1.]
 [ 0.  1.  0. -1.  0.]
 [ 0. -1. -1.  0.  0.]] 

[16, 30, 99, 99, 16, 72, 58, 30, 30, 1, 57, 86, 58, 1, 1, 57]
[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  0. -1.  1.]
 [ 0.  0.  1.  0.  1.]
 [ 0.  1.  0. -1. -1.]
 [ 0. -1. -1.  0.  0.]] 

[1, 79, 67, 116, 1, 79, 41, 78, 1, 1, 28, 67, 1, 80, 15

Game 46 Done 8 889
[25, 48, 71, 48, 71, 48, 140, 25, 71, 70, 25, 1, 93, 48, 25, 1, 25, 48, 71, 48, 48, 1, 48, 25, 48]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 

[1, 46, 68, 24, 1, 24, 24, 1, 46, 24, 24, 112, 1, 24, 90, 68, 68, 90, 111, 1, 46, 46, 89, 90]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0. -1.  0.  0.]] 

[23, 86, 1, 1, 86, 44, 65, 44, 23, 1, 44, 1, 23, 44, 86, 107, 85, 44, 86, 23, 44, 1, 107]
[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0. -1.  0.  0.]] 

[22, 61, 62, 42, 22, 22, 82, 42, 82, 22, 22, 1, 82, 22, 22, 82, 121, 1, 42, 42, 82, 42]
[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0. -1.  0.]
 [ 0.  0. -1.  0.  0.]] 

[1, 21, 59, 59, 21, 21, 59, 97, 59, 40, 21, 59, 40, 58, 59, 78, 21, 40, 40, 21, 97]
[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  1. 

[20, 74, 56, 38, 38, 38, 38, 56, 55, 20, 38, 56, 73, 56, 38, 56, 56, 1, 74, 38]
[[ 0.  0.  0.  0.  0.]
 [ 0. -1.  0.  1.  0.]
 [-1.  0.  1.  0.  0.]
 [ 0. -1.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.]] 

[53, 104, 19, 70, 1, 19, 53, 19, 36, 1, 120, 87, 87, 19, 36, 53, 53, 36, 1]
[[ 0.  0.  0.  0.  0.]
 [ 0. -1.  1.  1.  0.]
 [-1.  0.  1.  0.  0.]
 [ 0. -1.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.]] 

[34, 81, 1, 65, 82, 66, 66, 1, 34, 66, 50, 82, 18, 1, 66, 1, 66, 34]
[[ 0.  0.  0.  0.  0.]
 [ 0. -1.  1.  1.  0.]
 [-1.  0.  1.  0.  0.]
 [ 0. -1.  0.  1.  0.]
 [ 0.  0. -1.  0.  0.]] 

Game 1 Done 9 1100
[1, 48, 48, 25, 25, 185, 25, 25, 25, 71, 71, 48, 25, 1, 71, 93, 94, 48, 94, 48, 25, 1, 71, 1, 1]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 

[46, 46, 46, 68, 24, 24, 67, 46, 111, 46, 1, 90, 1, 1, 68, 46, 46, 46, 90, 24, 24, 68, 46, 46]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [-1.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]] 


[56, 74, 92, 20, 38, 56, 1, 20, 74, 1, 38, 38, 38, 74, 56, 56, 56, 20, 56, 56]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  1. -1.  0.]
 [-1.  0.  1.  0. -1.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]] 

no children
[19, 53, 1, 36, 137, 36, 36, 36, 36, 87, 53, 1, 87, 53, 1, 53, 36, 53, 53]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  1. -1.  0.]
 [-1.  0.  1.  0. -1.]
 [ 0.  1.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.]] 

Game 7 Done 8 794
[25, 1, 1, 25, 116, 25, 116, 25, 71, 48, 48, 1, 140, 25, 48, 71, 116, 25, 48, 25, 1, 25, 1, 48, 94]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 

[90, 24, 24, 24, 46, 24, 1, 24, 24, 112, 68, 46, 68, 68, 133, 1, 46, 46, 24, 46, 68, 46, 46, 24]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [-1.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]] 

[1, 23, 23, 23, 1, 86, 86, 23, 44, 23, 85, 65, 86, 65, 44, 85, 107, 1, 44, 23, 23, 23, 86]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [-1.  0.  1.  0.  0.]
 [ 0.  1.  0

[82, 22, 81, 42, 62, 1, 101, 62, 62, 42, 22, 22, 1, 22, 22, 22, 42, 42, 122, 62, 62, 22]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0. -1.  1. -1.  0.]
 [ 0.  0.  0.  0.  0.]] 

[1, 1, 59, 59, 40, 59, 78, 1, 59, 59, 78, 97, 59, 21, 59, 40, 59, 78, 1, 59, 1]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0. -1.  1. -1.  0.]
 [ 0.  0.  1.  0.  0.]] 

Game 13 Done 6 426
[1, 48, 48, 71, 1, 1, 48, 1, 140, 71, 1, 48, 208, 1, 48, 71, 94, 1, 25, 71, 25, 48, 48, 25, 25]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 

[24, 24, 68, 24, 46, 46, 68, 1, 46, 24, 46, 90, 67, 111, 1, 90, 46, 46, 24, 1, 68, 46, 68, 46]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [-1.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]] 

[65, 23, 65, 44, 65, 106, 23, 44, 23, 23, 44, 23, 64, 86, 23, 85, 65, 44, 1, 65, 44, 23, 23]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [-1.  0.  1.  0.  0.]
 [ 0.  1.  0

[65, 23, 23, 86, 65, 44, 23, 23, 23, 86, 65, 44, 65, 65, 44, 44, 23, 86, 23, 44, 1, 65, 44]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0. -1.  0.]
 [ 0.  0.  1.  0.  0.]] 

[62, 62, 62, 22, 42, 82, 62, 62, 1, 62, 22, 62, 22, 22, 42, 22, 102, 22, 82, 1, 42, 62]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0. -1.  0. -1.  0.]
 [ 0.  0.  1.  0.  0.]] 

no children
[116, 77, 40, 21, 59, 135, 21, 1, 59, 21, 40, 59, 21, 59, 21, 1, 40, 96, 21, 1, 59]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0. -1.  0. -1.  0.]
 [ 0.  0.  1.  1.  0.]] 

[1, 56, 38, 38, 38, 1, 56, 20, 38, 110, 56, 38, 56, 92, 74, 1, 38, 56, 92, 20]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [-1. -1.  0. -1.  0.]
 [ 0.  0.  1.  1.  0.]] 

no children
[36, 19, 36, 36, 36, 36, 136, 36, 36, 36, 104, 53, 19, 70, 1, 70, 103, 1, 1]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [-1. -1.  0. -

[52, 53, 19, 19, 69, 36, 53, 70, 70, 70, 53, 69, 53, 1, 19, 36, 121, 1, 1]
[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [-1.  0.  1.  0.  0.]
 [-1. -1.  0.  0.  0.]
 [ 0.  0.  1.  1.  0.]] 

[50, 66, 18, 34, 18, 1, 18, 82, 97, 18, 113, 129, 1, 98, 18, 1, 18, 34]
[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [-1.  0.  1.  0.  0.]
 [-1. -1.  0. -1.  0.]
 [ 0.  0.  1.  1.  0.]] 

[1, 47, 32, 32, 32, 77, 77, 47, 47, 62, 75, 135, 1, 1, 92, 1, 1]
[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [-1.  0.  1.  0.  0.]
 [-1. -1.  0. -1.  0.]
 [ 0.  1.  1.  1.  0.]] 

Game 25 Done 10 1263
[1, 71, 94, 25, 48, 94, 48, 48, 25, 48, 70, 48, 25, 25, 117, 48, 94, 25, 25, 48, 25, 25, 25, 25, 48]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 

[68, 68, 46, 68, 68, 24, 46, 46, 112, 89, 24, 24, 46, 1, 68, 68, 46, 46, 1, 24, 24, 46, 24, 46]
[[ 0.  0.  0.  0.  0.]
 [ 0. -1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]] 

[44, 

KeyboardInterrupt: 

In [6]:
player_challenger.wins

76